### ISSUE TITLE
Question: K8s components monitoring

### ISSUE THREAD

**Issue by lukasmrtvy** [cablespaghetti/k3s-monitoring#2]
Hello, why did You disabled https://github.com/cablespaghetti/k3s-monitoring/blob/master/kube-prometheus-stack-values.yaml#L1-L6 ? 

You can use:
```
  kubeEtcd:
    enabled: false
  kubeControllerManager:
    endpoints:
    - 88.XX.XX.XX
  kubeScheduler:
    endpoints:
    - 88.XX.XX.XX
  kubeProxy:
    endpoints:
    - 88.XX.XX.XX
```
, it will create Service/Endpoints in kube-system, what is problematic that ip in Endpoints does not allow FQDN, so You have to know IP address apriori. For example Service/Endpoints kubelet is created with that IP by operator automatically. 

EDIT: seems these are scraped via apiserver and proxy ?
