### ISSUE TITLE
Embedded etcd monitoring

### ISSUE THREAD

**Issue by cablespaghetti** [cablespaghetti/k3s-monitoring#4]
Currently can't monitor embedded etcd when that is enabled. When a release of k3s has been cut with this PR, we can revisit.

https://github.com/k3s-io/k3s/pull/2750

**Comment by cablespaghetti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [k3s: Embedded etcd monitoring](https://trello.com/c/A1xqg0oq/20-k3s-embedded-etcd-monitoring)

**Comment by plsnotracking** [comment]
Looks like the underlying PR has been merged, is it okay to now enable the etcd metrics?

**Comment by knweiss** [comment]
FWIW: I've just tested this successfully with k3s v1.22.6+k3s1 (stable channel).

I.e. start k3s with `--etcd-expose-metrics=true` and then configure the local kube-prometheus-stack-32.2.1 `values.yaml` to a) enable `kubeEtcd` b) list the IP endpoints of the k3s server nodes where embedded etcd is running and c) switch the etcd port from 2379 to 2381.
```
kubeEtcd:
  enabled: true

  ## If your etcd is not deployed as a pod, specify IPs it can be found on
  ##
  endpoints:
    - ...insertyourips...
    - ...insertyourips...
    - ...insertyourips...

  ## Etcd service. If using kubeEtcd.endpoints only the port and targetPort are used
  ##
  service:
    enabled: true
    port: 2381
    targetPort: 2381
```
