### ISSUE TITLE
Adding extra scrape configuration options does not reflect change

### ISSUE THREAD

**Issue by plsnotracking** [cablespaghetti/k3s-monitoring#7]
First of all, thank you for making this tutorial and the repo.

At the end of this file: https://raw.githubusercontent.com/cablespaghetti/k3s-monitoring/master/kube-prometheus-stack-values.yaml

I add:
```
extraScrapeConfigs: |
- job_name: 'pihole'
    static_configs:
      - targets: ['localhost:9617']
```
But the configmap doesn't list this after I upgrade my helm chart with the new values. Any suggestions/pointer on what I'm doing incorrectly?

I'm trying to add this (https://github.com/eko/pihole-exporter) to my prometheus targets and have a dashboard ready to reaad from prometheus.

Thank you.
